services:
  gigmaster:
    build: .
    container_name: gigmaster
    ports:
      - "3000:3000"
    volumes:
      # local lyrics folder
      - ./lyrics:/app/lyrics
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    user: ${CURRENT_UID}
